# Generated by Django 3.0.4 on 2020-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfrom', models.CharField(default='', max_length=100)),
                ('userto', models.CharField(default='', max_length=100)),
                ('header', models.CharField(default='', max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
